Imbalanced Dataset:
A dataset with unequal class distribution
ex : suppose in a diabete datset we have 1000 data points of non-diabetic person and only 100 data points of diabatic person

In [2]:
import pandas as pd
import numpy as np

In [3]:
credit_card_data = pd.read_csv("/content/credit_data.csv")

In [10]:
credit_card_data.shape

(73377, 31)

In [7]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [5]:
# last 5 rows of dataset
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
73372,55105,1.104021,-1.123835,1.008939,-0.460960,-1.502758,0.021138,-1.055043,0.095135,-0.175413,...,0.405906,1.054006,-0.174455,0.155852,0.358077,-0.030114,0.048490,0.042121,119.00,0.0
73373,55105,1.182898,-0.283273,1.123494,0.066948,-1.283276,-0.900451,-0.441870,-0.150647,0.784691,...,0.082278,0.491790,-0.025468,1.078368,0.258355,1.415871,-0.060454,0.014606,22.71,0.0
73374,55106,1.168124,-0.122507,1.251822,0.860341,-1.020137,-0.277310,-0.557856,0.023732,0.802378,...,-0.077921,-0.005984,0.014309,0.452036,0.281031,0.313100,0.020995,0.030389,16.35,0.0
73375,55106,-0.339385,-2.095670,0.271543,-3.066469,0.484794,3.870704,-2.069399,0.184347,-1.615958,...,0.964115,-0.266112,-0.993763,1.033766,0.748706,-0.116168,0.153607,0.268881,322.34,0.0
73376,55107,-1.020407,0.160171,0.152264,-0.093406,-0.978017,0.074549,1.610152,0.117407,-0.948643,...,0.109380,-0.400171,0.835422,-0.428141,-0.464220,NaN,NaN,NaN,NaN,NaN

In [12]:
# distribution of the two classes
credit_card_data["Class"].value_counts()

Class
0.0    73198
1.0      178
Name: count, dtype: int64

This is highly inbalnced data set

0--> Legit transctions
1--> Fraudulent transactions

In [16]:
# separating the legit and fraudulent transaction
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [17]:
legit.shape

(73198, 31)

In [19]:
fraud.shape

(178, 31)

Under-Sampling

Buid a sample dataset containing similar distribution of Legit and Fraudulent transactons

Number of fraudulent transactons : 178

In [21]:
legit_sample = legit.sample(n=178)

In [22]:
print(legit_sample.shape)

(178, 31)

Concatenate two data frames

In [28]:
new_credit_card_dataset = pd.concat([legit_sample, fraud], axis=0)

In [34]:
new_credit_card_dataset.shape

(356, 31)

In [35]:
new_credit_card_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
37291,38895,-0.881081,0.219706,1.619924,-0.545692,1.353764,-0.886284,0.632757,-0.261069,-0.353389,...,-0.217760,-0.712651,-0.103660,-0.460922,-0.031996,-0.037914,-0.146680,-0.112008,1.98,0.0
18516,29560,1.350967,-0.721958,-0.334705,-1.049059,-0.247971,0.269552,-0.590564,0.118119,-0.931101,...,0.225348,0.461017,-0.261345,-1.139708,0.636213,-0.032210,-0.008257,-0.010760,47.70,0.0
47852,43389,1.084320,-1.237842,1.022659,-0.508855,-1.738414,-0.145324,-1.141654,0.163718,-0.265756,...,0.423219,0.956203,-0.212341,0.381512,0.360233,-0.074492,0.019102,0.034706,129.00,0.0
41141,40555,1.045278,-0.303990,-0.488719,0.013595,-0.150374,-0.871170,0.472007,-0.238758,-0.330529,...,0.057221,-0.169345,-0.251322,0.074305,0.500288,1.061212,-0.145975,-0.000446,140.45,0.0
5856,6368,-1.425079,0.330939,2.312133,-2.715652,-0.476413,-0.750138,0.014072,-0.074900,3.379051,...,-0.081584,0.470853,-0.320473,-0.166946,0.579546,-0.016587,0.300723,0.090907,14.98,0.0

In [36]:
new_credit_card_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
69498,53451,0.385108,1.217620,-1.953872,2.087076,-1.144225,-0.576888,-2.582865,0.643230,-1.191233,...,0.594623,0.372144,-0.310456,-0.624065,0.840216,-0.159452,0.599482,0.288916,8.00,1.0
69980,53658,-1.739341,1.344521,-0.534379,3.195291,-0.416196,-1.261961,-2.340991,0.713004,-1.416265,...,0.383180,-0.213952,-0.336640,0.237076,0.246003,-0.044228,0.510729,0.220952,0.00,1.0
70141,53727,-1.649279,1.263974,-1.050826,2.237991,-2.527889,-0.889940,-2.355254,0.854659,-1.281243,...,0.679176,0.731907,0.333045,0.392505,-0.274197,0.802349,0.390809,0.112146,112.45,1.0
70589,53937,-2.042608,1.573578,-2.372652,-0.572676,-2.097353,-0.174142,-3.039520,-1.634233,-0.594809,...,-0.723326,0.501222,-0.696892,-0.600514,0.127547,-0.786072,0.606097,0.171697,261.87,1.0
72757,54846,-2.986466,-0.000891,0.605887,0.338338,0.685448,-1.581954,0.504206,-0.233403,0.636768,...,-0.875146,-0.509849,1.313918,0.355065,0.448552,0.193490,1.214588,-0.013923,1.79,1.0

In [37]:
new_credit_card_dataset["Class"].value_counts()

Class
0.0    178
1.0    178
Name: count, dtype: int64